### ISSUE TITLE
TravisBuddy cannot obtain log excerpts from Matrix builds

### ISSUE THREAD

**Issue by silasary** [bluzi/travis-buddy#109]
We recently changed our travis setup to include a build matrix, producing builds like [this one](https://travis-ci.org/PennyDreadfulMTG/Penny-Dreadful-Tools/builds/389162327)

Unfortunately, TravisBuddy is able to get logs out of these kinds of builds, and leaves us with unsatisfying comments like [this](https://github.com/PennyDreadfulMTG/Penny-Dreadful-Tools/pull/4705#issuecomment-385146489)

**Comment by bluzi** [comment]
Hey @silasary,

Thanks for creating this issue, this is not the first time we handle issues related to the different methods of configuration of scripts in `.travis.yml`.
For some reason, Travis offers super flexible configuration, and that makes it hard for us to handle all the possibilities.

Anyway, I'll fork your repository over the weekend so I can debug your configuration.

Thanks for reporting, please feel free to share more feedback if you have any. :)

**Comment by silasary** [comment]
Any luck reproducing this?

**Comment by bluzi** [comment]
@silasary @bakert 

Hey guys, sorry for leaving you hanging for so long, I was real busy in the last two months. 
I'm glad to say I had a look and resolved the issue.

After the next deployment (about 30 minutes from now) you should start receiving valid comments from TravisBuddy. 

I'll monitor your repository in the next few days to make sure everything is alright, but if you see something unexpected please let me know.

I'll close this issue after your confirmation.

**Comment by silasary** [comment]
Awesome, that works 😃
I have a feature request, to make the headings do variable expansion, but that's a separate, less important issue. I'll open a new issue for it

**Comment by SilleBille** [comment]
Just wanted to check on this. So, this feature will excerpt the logs from the failed job, right? What happens if there are multiple failing jobs in a matrix? 

Or did I misunderstand the pipeline?
