### ISSUE TITLE
Add link to Travis log

### ISSUE THREAD

**Issue by jayvdb** [bluzi/travis-buddy#115]
If the log excerpt is not sufficient, or the log except is missing (https://github.com/bluzi/travis-buddy/issues/109), it would be nice to have a link to the log on Travis.  This would help when looking at problems in old PRs where the travis build is no longer listed at the top of its PR list.

**Comment by Rylon** [comment]
This would be nice, yes 👍

**Comment by bluzi** [comment]
Done and active in production

**Comment by Rylon** [comment]
Awesome, thanks @bluzi!
