### ISSUE TITLE
Creates links to wrong Travis-CI site / non-existent builds

### ISSUE THREAD

**Issue by mprins** [bluzi/travis-buddy#160]
TravisBuddy creates links to log files and builds that don't exist.

Some time ago Travis [announced to move everything to their .com domain](https://blog.travis-ci.com/2018-05-02-open-source-projects-on-travis-ci-com-with-github-apps), I have recently moved all our open source projects over and am [now looking at TravisBuddy](https://github.com/B3Partners/brmo/pull/780). I see TravisBuddy generates links to non-existing builds, on the travis-ci.org domain while links should be generated to the travis-ci.com domain.

generated link: `https://travis-ci.org/B3Partners/brmo/builds/145258230`
but should be: `https://travis-ci.com/B3Partners/brmo/builds/145258230`

I suspect one of these hardcoded urls is the culprit:

https://github.com/bluzi/travis-buddy/blob/de342b91f8013a538648b5913d9d7e81f56a9809/pipes/parse-travis-payload.pipe.js#L17

https://github.com/bluzi/travis-buddy/blob/de342b91f8013a538648b5913d9d7e81f56a9809/pipes/parse-travis-payload.pipe.js#L98

examples: 

- https://github.com/B3Partners/brmo/pull/780#issuecomment-576446890 
- https://github.com/B3Partners/brmo/pull/780#issuecomment-576448150

**Comment by bluzi** [comment]
Thanks @mprins, I've fixed it here: https://github.com/bluzi/travis-buddy/commit/1a06d327b7a1e55a840cd106715c52a636102bfc
