### ISSUE TITLE
Question about allowed to fail jobs

### ISSUE THREAD

**Issue by kenman345** [bluzi/travis-buddy#46]
Hi,

So I have not used the bot yet but it looks like exactly what I am looking for. I was wondering though what happens if I have allowed_failure jobs and those fail but the others pass? Would I still get a notification? We have some validations we want to know about to make sure links are not dead or data in alphabetical order but they're not hard stops to being able to merge a PR or not. So, can we still get those to notify the PR so if they do them great, but otherwise its okay?

I do not see much documentation about how it handles jobs, would I need to handle all results I want to be notified about in the same job now?

**Comment by bluzi** [comment]
Hey @kenman345,

We actually never tested `allow_failures` before. I can tell you that [as you can see here](https://github.com/bluzi/travis-buddy/blob/32326b36ded12d2bb2e5bdfa5bf015d29f56dcf4/routes/api.routes.js#L35), @TravisBuddy only comments on PR if the Travis returns `failure` as the status for the whole PR, so my guess is that @TravisBuddy won't create a comment if all the jobs are successful except does that are allowed to fail, but feel free to make this experiment yourself. If you won't like the result, contact me here and I can help by making the changes code-wise. 

Hope this helps.

**Comment by kenman345** [comment]
Yea, I'm wondering if I'd need my main build to run test scripts only when its a PR just to allow this functionality. I normally test on a forked repo of the main repo but it seems travisbuddy follows the repos and I dont need my public repo gaining traction or anything. 

What about multiple jobs and success notifications are enabled? Would it grab logs from all three of my jobs?

**Comment by bluzi** [comment]
No it won't, it'll create one comment

**Comment by kenman345** [comment]
So If my tests are just a ruby script I wrote? will it identify these as checks? I see your repo uses Jasmine to test things, which is more of a framework that I wouldnt need. 

Perhaps it might be useful if I could test this on my personal public repo, but could you unfollow the repo for me if I do?

**Comment by bluzi** [comment]
Hello @kenman345,

Sorry for the late response, it's been a busy week.

You don't have to use a test framework in order to use @TravisBuddy, a simple Ruby script (or any other code supported by Travis) is just fine - just make sure to print some logs and @TravisBuddy will include these logs in its comment.

Not sure what you mean by "unfollow the repo", but if you need anything - I'll do my best to assist.
