### ISSUE TITLE
How do you get author name?

### ISSUE THREAD

**Issue by mzfr** [bluzi/travis-buddy#48]
I am working on a tool similar to travis buddy.  Travis doesn't provide the pull request author name by default: https://docs.travis-ci.com/user/environment-variables/#Default-Environment-Variables

So, how does travis buddy figure out the user? (as seen in the screenshot)

**Comment by bluzi** [comment]
Hey @mzfr,

Travis actually provides the author name in the payload, as seen in this example payload: https://github.com/bluzi/travis-buddy/blob/master/sample-payloads/payload2.json#L45

If a full name is not available, Travis will provide the nickname instead. 

Hope this helps
