### ISSUE TITLE
Convert asynchronous functions to async/await syntax 

### ISSUE THREAD

**Issue by bluzi** [bluzi/travis-buddy#51]
Currently, there are many of async operations in the project, and unfortunately I didn't wrote it using the newer async/await syntax.
Since now it's fully supported by Node, I will find it must more easy to maintain if it'll be implemented using this syntax.

This is a great first issue, feel free to jump in.

**Comment by Eddie-CooRo** [comment]
I'd like to help with this issue

**Comment by Eddie-CooRo** [comment]
Hi
I'd like to help with this issue
