### ISSUE TITLE
Message on succesful build

### ISSUE THREAD

**Issue by LuisFernando100** [bluzi/travis-buddy#67]
Hello, I am trying to make a success message which I am seeing from previous commits that it is implemented but I have not been able to make it work. The system works on failed builds and the comments are created according to the template on the root directory, but on success no message is made at all.

I would like to know if this is a bug, the feature is not finished being implemented yet, or I am doing something wrong. The name for the success template I am using is "travis-buddy-success-template.md" and the contents are the same as the template shown as the example in this repository. Obviously I dont have "on success: never" added in my travis and the default as shown in the Travis documentation webpage is "always".

Thanks for the help.

**Comment by bluzi** [comment]
Hey @LuisFernando100,

This is a known bug we're facing, the success message feature is not widely used by repositories, as disabling it reduces spam and noise, and therefore it was barely tested in production, so we only found out it's broken few days ago. (Thanks to @nemchik)

Thanks for opening this issue, I'll let you know when its solved and tested on a fork of your repository.

**Comment by bluzi** [comment]
@LuisFernando100,

I deployed the fix, you should start receiving success messages.

**Comment by LuisFernando100** [comment]
Yeah, it works now, thanks.

For the future, a similar feature for success templates could be made, but if its not widely used as you said then I guess for now its more than enough.

**Comment by bluzi** [comment]
Hey @LuisFernando100, I agree, [added](https://github.com/bluzi/travis-buddy/pull/70).
