### ISSUE TITLE
"Deploy to Heroku" button

### ISSUE THREAD

**Issue by bluzi** [bluzi/travis-buddy#74]
Add "Deploy to Heroku" button to `README.md`

https://devcenter.heroku.com/articles/heroku-button

**Comment by alejandronanez** [comment]
I can take this if you don't mind!

**Comment by bluzi** [comment]
Sure @alejandronanez, thanks

**Comment by bluzi** [comment]
Are you handling it @alejandronanez?

**Comment by alejandronanez** [comment]
Hey @bluzi, I read a little bit about it but I was short of time the last couple of days. I think I can take a look at it finally today or tomorrow tops.
