### ISSUE TITLE
TravisBuddy only one comment in Pull Request

### ISSUE THREAD

**Issue by maracuja-juice** [bluzi/travis-buddy#89]
This is a feature request.

Let's say a build fails twice: 

- **Expected Behaviour:**
Travis Buddy only comments once and updates his comment. (Similar to how Codecov does this)
- **Current Behaviour:**
What Travis Buddy does is comment 2 times on the pull request.

This way there will be less "_spam_" and with this featureI would disable the "on_success" flag.

This could either be the new standard behaviour or also enabled/disabled via a new flag. What do you think?

And btw: I really like the work you made here!

**Comment by bluzi** [comment]
Hey @maracuja-juice,

First of all, thanks!

Second,
I'm glad to say the feature you're requesting is already implemented and live in production!
[As you can see](https://github.com/bluzi/travis-buddy/issues/72), I implemented this few days ago. It still haven't been tested on a real repository in production, but feel free to try it yourself and be an alpha tester :) 

Just change the webhook in your `.travis.yml` to be: `https://www.travisbuddy.com/?insert=update` and see if it works. 

I'm closing for now, but please report back if you give it a try :)

**Comment by maracuja-juice** [comment]
Hey that's really cool. I will try this 9ut and report back.
If you want I can add this to the docs after I tested it

**Comment by bluzi** [comment]
@maracuja-juice I'm afraid I mislead you: it's `https://www.travisbuddy.com/?insertMode=update`, not `?insert=update`. My bad!

**Comment by maracuja-juice** [comment]
Oh okay. Just wanted to tell you that it doesn't work :)

**Comment by maracuja-juice** [comment]
Hmm am I doing something wrong or why is he still commenting twice? 
See here:
https://github.com/maracuja-juice/notifications-for-spotify/pull/52

**Comment by bluzi** [comment]
Hey, you're not doing anything wrong, I tested it myself and it doesn't work for some reason. I'll have a look later today.

**Comment by bluzi** [comment]
Finally solved it: https://github.com/bluzi/travis-buddy/pull/100

Please let me know if it works for you now

**Comment by maracuja-juice** [comment]
Hey cool that works now! (just tested it on the pull I linked above)
I also had a small look into the code for this yesterday but couldn't see anything wrong in the code. Would like to know how you solved it in the end.

**Comment by bluzi** [comment]
Glad to hear it works :) 

The issue caused because of the way we used to cache the comments of an issue, a bug caused the cache to live forever, and so TravisBuddy couldn't tell there's already a comment.
